### PR TITLE
Close the AudioContext on stop

### PR DESCRIPTION
**Pull request by ktsour**
Browsers have limits on how many AudioContexts are open. Safari only 4, Chrome 30. We need to close the AudioContexts on stop if we need to start new recordings.

### CODE REVIEW

**Comment by ktsour** [comment]
Hi,

We are overwhelmed with projects and cannot find the time to do the check.
We are not using it like this, so we will not have any issue.

Sorry for not being able to assist further on this!

BR
Kiriakos

**Comment by eliasmeire** [comment]
Closing this, will fix this in v4. Workaround is available in v3 by using the `audioContext` option in the constructor

**Comment by Morsmetus** [comment]
@eliasmeire Can you please elaborate more about workaround ?

**Comment by eliasmeire** [comment]
Hi @Morsmetus 

in the constructor of the `Mp3MediaRecorder` class you can pass an instance of `AudioContext`.
(https://github.com/eliasmeire/mp3-mediarecorder/blob/master/src/recorder.ts#L43)

for example

```ts
const audioCtx = new AudioContext();
const recorder = new Mp3MediaRecorder(stream, { audioContext: audioCtx })
```

You can then close the AudioContext yourself whenever you want, for example on stop

```ts
recorder.onstop = () => audioCtx.stop();
```

**Pull request closed without merging**
